service: my-lambda-service
provider:
  name: aws
  runtime: nodejs12.x
functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: get
  imageResize:
    handler: handler.imageresize
    events:
      - http:
          path: /imageresize
          method: get
